modLoader="javafml"
loaderVersion="[37,)"
license="MIT License"
issueTrackerURL="https://github.com/MapperTV/mapperbase/issues"
[[mods]]
modId="mapperbase"
version="${file.jarVersion}"
displayName="Mapper Base"
#updateJSONURL="http://myurl.me/"
displayURL="http://mapper.tv/minecraft/mapperbase"
logoFile="mapperbase_logo.png"
credits="The Forge team and community for the help and resources."
authors="Mapper"
description="This mod simply provides the basic elements for my other mods to avoid duplicate elements."

[[dependencies.mapperbase]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mapperbase]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"
